name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      VITE_SPACETIME_HOST: ${{ vars.VITE_SPACETIME_HOST }}
      VITE_SPACETIME_MODULE: ${{ vars.VITE_SPACETIME_MODULE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint:all

      - name: Build
        run: bun run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v2.x

      - name: Check
        run: deno task check

      - name: Lint
        run: deno task lint

      - name: Test
        run: deno task test

  stdb:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stdb
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2.8.2
        with:
          workspaces: stdb

      - name: Check
        run: cargo check

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build
